# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 3950x
  vmImage: 3950x

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMPipeline-conn'
    subscriptionId: 'd1f0c2dc-a3b9-495a-92fa-be44caa31b3a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMPipeline-rg'
    location: 'UK South'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/jaseruk/AzureDeploy/main/create_web_app/azuredeploy.json'
    overrideParameters: '-projectName jrdeploy -storageSKU Standard_ZRS'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipeLineTemplate'